### PR TITLE
fix deadlock in processWriteQueue

### LINKED ISSUE #777: deadlock in processWriteQueue
```
goroutine 796 [select, 2231 minutes]:
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Conn).exec(0xc420a9e000, 0x0, 0x0, 0x1025720, 0xc4345e1f10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/conn.go:637 +0x74f
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Conn).executeQuery(0xc420a9e000, 0xc430732200, 0xc407cc7dfe)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/conn.go:830 +0x575
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).execute(0xc430732200, 0xc420a9e000, 0x1069b20)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:750 +0x35
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc420986180, 0x1033660, 0xc430732200, 0xc42f7a0013, 0x3, 0xc427de7c68)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/query_executor.go:42 +0x1b3
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Session).executeQuery(0xc420184280, 0xc430732200, 0xc427de7c00)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:376 +0xc1
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).Iter(0xc430732200, 0xc430732200)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:921 +0xbf
github.com/raintank/metrictank/vendor/github.com/gocql/gocql.(*Query).Exec(0xc430732200, 0xc42b09f1d0, 0x45)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/gocql/gocql/session.go:904 +0x2b
github.com/raintank/metrictank/mdata.(*CassandraStore).insertChunk(0xc42089a600, 0xc4240dcf30, 0x26, 0xa8c005a2627d0, 0xc43c631520, 0x4a, 0xc8, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:370 +0x467
github.com/raintank/metrictank/mdata.(*CassandraStore).processWriteQueue(0xc42089a600, 0xc420a881e0, 0xc420bcc0e0)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:309 +0x398
created by github.com/raintank/metrictank/mdata.NewCassandraStore
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/mdata/store_cassandra.go:267 +0x1008
```

gocql is getting into a deadlock state.

see also #726

### PR DESCRIPTION
**Pull request by woodsaj**
fixes #777

### CODE REVIEW

**Comment by replay** [comment]
LGTM

**Comment by Dieterbe** [comment]
the way to update a library is now like so:
```
dep ensure -update <importpath>; dep prune
```

File: mdata/store_cassandra.go [hunk 1]
```diff
@@ -584,9 +588,14 @@ LOOP:
...
 		err := outcome.i.Close()
 		if err != nil {
+			if err == context.Canceled || err == context.DeadlineExceeded {
+				// query was aborted.
+				return nil, nil
+			}
 			tracing.Failure(span)
 			tracing.Error(span, err)
 			errmetrics.Inc(err)
+			return nil, err
```
Comment (Dieterbe) [inline mdata/store_cassandra.go]: for better or worse, it used to be by design that we would continue here and just use as much data as we could get back.  remember the days before @replay started, and we would see charts with missing data here and there because certain chunks timed out? we would see the timeout errors on our MT dashboard, and MT always tried to make the most out of it.  
anyway the importance of "correct or error" (as opposed to "best effort") is become more and more clear as we see with some customers and their alerting queries. so :+1:

File: mdata/store_cassandra.go [hunk 2]
```diff
@@ -290,6 +291,7 @@ func NewCassandraStore(addrs, keyspace, consistency, CaPath, Username, Password,
 		omitReadTimeout:  time.Duration(omitReadTimeout) * time.Second,
 		ttlTables:        ttlTables,
 		tracer:           opentracing.NoopTracer{},
+		timeout:          cluster.Timeout,
```
Comment (Dieterbe) [inline mdata/store_cassandra.go]: note that we default to 1000 ms, this seems too aggressive. looking at some customer dashboards, some customers are seeing multi-second query durations (cassGetExecDuration)

File: mdata/store_cassandra.go [hunk 3]
```diff
@@ -584,9 +588,14 @@ LOOP:
 		}
 		err := outcome.i.Close()
 		if err != nil {
+			if err == context.Canceled || err == context.DeadlineExceeded {
+				// query was aborted.
+				return nil, nil
+			}
 			tracing.Failure(span)
 			tracing.Error(span, err)
 			errmetrics.Inc(err)
```
Comment (Dieterbe) [inline mdata/store_cassandra.go]: this line triggers this code:
```
func (m *ErrMetrics) Inc(err error) {
	if err == gocql.ErrTimeoutNoResponse {
		m.cassErrTimeout.Inc()
	} else if err == gocql.ErrTooManyTimeouts {
		m.cassErrTooManyTimeouts.Inc()
	} else if err == gocql.ErrConnectionClosed {
		m.cassErrConnClosed.Inc()
	} else if err == gocql.ErrNoConnections {
		m.cassErrNoConns.Inc()
	} else if err == gocql.ErrUnavailable {
		m.cassErrUnavailable.Inc()
	} else if strings.HasPrefix(err.Error(), "Cannot achieve consistency level") {
		m.cassErrCannotAchieveConsistency.Inc()
	} else {
		m.cassErrOther.Inc()
	}
}
```
seems weird that various gocql timeouts result in err metrics being incremented, whereas context.DeadlineExceeded does not. I think we should also increment a timeout metric when context.DeadlineExceeded triggers

File: mdata/store_cassandra.go (hunk 2 above)
Comment (woodsaj) [reply mdata/store_cassandra.go]: 1) this timeout is only used for writes.  reads just use the existing requestContext, which we dont currently set a timeout on and instead just rely on the context being canceled, eg when the client disconnects.

2) queries will fail if they run longer then cluster.Timeout. 
 https://github.com/grafana/metrictank/blob/ca4a891be799a2aafb5f70ba10738eac9871050b/vendor/github.com/gocql/gocql/conn.go#L612-L658

So if we have queries that are running longer then this, then it will be because they are blocked waiting for a stream to become available.

File: mdata/store_cassandra.go (hunk 3 above)
Comment (woodsaj) [reply mdata/store_cassandra.go]: store_cassandra.go does not set a context Timeout on the read path. 

So if context.Canceled or context.DeadlineExceeded is returned,  it is because the caller wanted us to give up on the request.  There was no issue preventing us from executing the request.

currently, we dont set a deadline on the request context anywhere, so context.DeadlineExceeded will never be returned.  It is just here for completeness incase we oneday add a deadline to the context.

File: mdata/store_cassandra.go (hunk 2 above)
Comment (Dieterbe) [reply mdata/store_cassandra.go]: 1. ah yes..
2. in insertChunk we call `context.WithTimeout(context.Background(), c.timeout)`
doesn't that mean that in the select either of the 2 operations (between lines 648 and 655 in the code shown above) can succeed at practically the same time?

one comes from the timeout set from `c.timeout` which is the same timeout value we specified in the config, whereas the ctxDone fires when the context's deadline triggers, which is a deadline we set also based on the same timeout?

IOW i don't see the use for the context on the insert queries since they seem to achieve the same as the already setup timeout mechanism. am i missing something?

File: mdata/store_cassandra.go (hunk 3 above)
Comment (Dieterbe) [reply mdata/store_cassandra.go]: wouldn't we want context.DeadlineExceeded to mark the spans as failed and the ErrMetrics to be incremented? it seems to me any such deadline being hit is a failure that should be reported

Comment (woodsaj) [reply mdata/store_cassandra.go]: No.  If DeadlineExceeded is reached it is because the caller set a timeout and they should emit their own error metrics and set the span to failed.

The error would have nothing to do with cassandra, so you should not increment the cassandraErr counters

File: mdata/store_cassandra.go (hunk 2 above)
Comment (woodsaj) [reply mdata/store_cassandra.go]: c.timeout is only measured from after the request is sent to cassandra.
the context.Deadline is set when the request is constructed, so includes the time the request sits waiting to be sent.

Comment (Dieterbe) [reply mdata/store_cassandra.go]: let's rename this field to `writeTimeout` to avoid confusion

File: mdata/store_cassandra.go (hunk 3 above)
Comment (Dieterbe) [reply mdata/store_cassandra.go]: fair enough

File: mdata/store_cassandra.go (hunk 2 above)
Comment (woodsaj) [reply mdata/store_cassandra.go]: > let's rename this field to writeTimeout to avoid confusion
No.  CassandraStore.timeout  is assigned the same value as the gocql cluster.Timeout, which is for reads and writes.

Variables should be named based on the information they contain, not on how they are used.

**Comment by woodsaj** [comment]
This is good to merge @Dieterbe
