### PR TITLE
Fix processing funcs changes affecting other targets + refactor all func tests to test for clobbering

### LINKED ISSUE #829: Some functions modify series' in place, which effects names in other functions
This is only an issue when the same target expression is used in a single request. For example:
`divideSeries(aliasByTags(seriesByTag('name=cpu.percent.idle','host=host1'),'host'),seriesByTag('name=cpu.percent.idle','host=host1')`

Note: the dividend is alias'd to the hostname, the divisor is not.

Graphite returns a name of:
`divideSeries(host1,cpu.percent.idle.g;host=host1)`

Metrictank returns:
`divideSeries(lxfsrvny1,lxfsrvny1)`

It seems the following expressions make in-place changes that effect all cached series:
[alias](https://github.com/grafana/metrictank/blob/master/expr/func_alias.go#L27)
[aliasByNode](https://github.com/grafana/metrictank/blob/master/expr/func_aliasbynode.go#L29)
[aliasSub](https://github.com/grafana/metrictank/blob/master/expr/func_aliassub.go#L33)

Additional Note: It seems that changing the single quotes to double quotes in the `seriesByTag` expression is enough to trick metrictank into fetching the series a second time and workaround that issue.

### PR DESCRIPTION
**Pull request by shanson7**
Fixes #829 

I went through and beefed up the tests / added test files where they didn't exist. I normalized them to generally look the same, which I think makes it easier when adding new functions or adding tests to existing functions. The new checks are for functions modifying series in place and double adding slices to the pool. Lots of functions modified series in place, but none double added slices.

For the functions that modified series in place, I fixed them. This was a bit tedious but I think over all it sets a better base for functions in the future.

### CODE REVIEW

File: expr/test.go [hunk 1]
```diff
@@ -9,6 +9,26 @@ import (
 
 var results []models.Series
 
+func equalTags(exp, got []models.Series) error {
+	for i, g := range got {
+		o := exp[i]
```
Comment (Dieterbe) [inline expr/test.go:14]: exp and got may have a different len?

File: expr/test.go [hunk 2]
```diff
@@ -9,6 +9,26 @@ import (
...
+		if len(g.Tags) != len(o.Tags) {
+			return fmt.Errorf("series %d: len tags expected %d, got %d", i, len(o.Tags), len(g.Tags))
+		}
+		for k, v := range g.Tags {
```
Comment (Dieterbe) [inline expr/test.go:18]: I really like https://github.com/google/go-cmp and think we should use it in more places.
e.g.
```
func TestHelloWorld(t *testing.T) {

        want := map[string]string{
                "foo": "bar",
        }
        got := map[string]string{
                "foo":   "bar",
                "extra": "hello",
        }

        if diff := cmp.Diff(want, got); diff != "" {
                t.Errorf("mismatch (-want +got):\n%s", diff)
        }
}
~

go test -v .                                                                                                                                                         ⏎
=== RUN   TestHelloWorld
    TestHelloWorld: main_test.go:20: mismatch (-want +got):
          map[string]string{
        + 	"extra": "hello",
          	"foo":   "bar",
          }
--- FAIL: TestHelloWorld (0.00s)
FAIL
FAIL	github.com/Dieterbe/sandbox/cmp_map	0.002s
FAIL
```

Comment (shanson7) [reply expr/test.go:18]: nifty!

File: expr/test.go (hunk 1 above)
Comment (shanson7) [reply expr/test.go:14]: Generally already checked, but I can add the check here.

File: expr/datamap.go [hunk 3]
```diff
@@ -25,3 +30,29 @@ func (dm DataMap) Clean() {
 		}
 	}
 }
+
+// CheckForOverlappingPoints runs through all series in the pool and makes sure there
+// are no series that are overlapping (otherwise returning them would cause issues)
+// This is not efficient and should probably only be called from tests
```
Comment (Dieterbe) [inline expr/datamap.go:36]: overlap is ambiguous here. it is easy to lead people to think about situations like
```
  ------
      -------
```
What we're really checking for here, is whether any series have pointslices backed by the same array.

Fun fact: it is in theory fine to have 2 series backed by the same array but use non-overlapping sections of that array. as long as we don't grow them to where we start overlapping. But I agree with your code that for simplicity we should also reject such cases.

File: expr/datamap.go [hunk 4]
```diff
@@ -25,3 +30,29 @@ func (dm DataMap) Clean() {
...
+func (dm DataMap) CheckForOverlappingPoints() error {
+	// First flatten series to make the logic easier
+	flatseries := make([]models.Series, 0, len(dm))
+	for _, series := range dm {
+		flatseries = append(flatseries, series...)
+	}
+
```
Comment (Dieterbe) [inline expr/datamap.go:43]:
```suggestion
// we leverage the fact here that for any given slice, if you reslice or subslice it - which may result in the first slot's
// address changing - the last slot of the backing array remains the same and can be used to find slices backed
// by the same array
```

File: expr/func_mock_test.go [hunk 5]
```diff
@@ -20,6 +20,9 @@ func (s FuncMock) Context(context Context) Context {
 }
 
 func (s FuncMock) Exec(dataMap DataMap) ([]models.Series, error) {
+	// func_get would retrieve this from the map (added at a higher layer)
+	// Mock should add `data` to properly mock the render path
+	dataMap.Add(Req{}, s.data...)
```
Comment (Dieterbe) [inline expr/func_mock_test.go:25]: this doesn't seem like the right place.
if we call this repeatedly, we will add the same data to datamap repeatedly, which is a contract violation.
adding to datamap should probably be handled in the caller

**Comment by Dieterbe** [comment]
Wow, what a herculean effort.
Clearly in general this is an improvement. I still need to process most of this PR, but i'll leave comments as I go along.

File: expr/data_test.go [hunk 6]
```diff
@@ -312,8 +312,18 @@ func getCopy(in []schema.Point) []schema.Point {
...
+func getSeries(target, patt string, data []schema.Point) models.Series {
+	return models.Series{
+		Target:     target,
+		QueryPatt:  patt,
+		Datapoints: getCopy(data),
+		Interval:   10,
+	}
+}
+
 func getQuerySeries(patt string, data []schema.Point) models.Series {
```
Comment (Dieterbe) [inline expr/data_test.go:324]: getQuerySeries and getTargetSeries are now equivalent. perhaps we should consolidate?

File: expr/func_absolute.go [hunk 7]
```diff
@@ -31,16 +31,19 @@ func (s *FuncAbsolute) Exec(dataMap DataMap) ([]models.Series, error) {
 		return nil, err
 	}
 
-	for i, serie := range series {
-		series[i].Target = fmt.Sprintf("absolute(%s)", serie.Target)
-		series[i].Tags = serie.CopyTagsWith("absolute", "1")
-		series[i].QueryPatt = fmt.Sprintf("absolute(%s)", serie.QueryPatt)
-		series[i].Datapoints = pointSlicePool.Get().([]schema.Point)
+	outSeries := make([]models.Series, 0, len(series))
```
Comment (Dieterbe) [inline expr/func_absolute.go:34]: I see your argument for consistency, but it does seem a bit silly to reallocate output slices when for each incoming series there is 1 outgoing. we could reuse the input slice

File: expr/datamap.go (hunk 3 above)
Comment (Dieterbe) [reply expr/datamap.go:36]: actually, thinking about this again, the name overlap is apt.
because the kind of pattern shown is exactly what you can get into with same-array-backed slices.
So let's keep the name

File: expr/func_absolute.go (hunk 7 above)
Comment (shanson7) [reply expr/func_absolute.go:34]: There is an existing code path that allows for the exact same slice to be passed to multiple target branches. That's exactly the issue in #829 

Now, that *could* be fixed as well, but the copy has to happen somewhere and we decided CoW a long time ago.

File: expr/func_divideseries_test.go [hunk 8]
```diff
@@ -35,7 +35,8 @@ func TestDivideSeriesSingle(t *testing.T) {
 		},
 		[]models.Series{
 			{
-				Target: "divideSeries(foo;a=a;b=b,bar;a=a1;b=b)",
+				Target:    "divideSeries(foo;a=a;b=b,bar;a=a1;b=b)",
+				QueryPatt: "divideSeries(foo;a=a;b=b,bar;a=a1;b=b)",
```
Comment (Dieterbe) [inline expr/func_divideseries_test.go:39]: can use the helper functions here?

File: expr/func_absolute.go (hunk 7 above)
Comment (Dieterbe) [reply expr/func_absolute.go:34]: ah yes. can you also update devdocs/expr.md to clarify that COW now applies to the full series structures being passed into functions.

**Comment by Dieterbe** [comment]
I think you missed one:
```
grep -R 'series\[i\]\.' expr/                                                                                                                                       ⏎
expr/func_sortbyname.go:	return ss.cmp(ss.series[i].Target, ss.series[j].Target)
expr/datamap.go:			if slicesOverlap(flatseries[i].Datapoints, flatseries[j].Datapoints) {
expr/func_nonnegativederivative.go:		series[i].Target = fmt.Sprintf("nonNegativeDerivative(%s)", serie.Target)
expr/func_nonnegativederivative.go:		series[i].QueryPatt = fmt.Sprintf("nonNegativeDerivative(%s)", serie.QueryPatt)
expr/func_nonnegativederivative.go:		series[i].Tags = serie.CopyTagsWith("nonNegativeDerivative", "1")
expr/func_nonnegativederivative.go:		series[i].Consolidator = consolidation.None
expr/func_nonnegativederivative.go:		series[i].QueryCons = consolidation.None
expr/func_nonnegativederivative.go:		series[i].Datapoints = out
```

File: expr/func_mock_test.go (hunk 5 above)
Comment (shanson7) [reply expr/func_mock_test.go:25]: Fair, but the caller for Mock is always tests, which would add to the code duplication. Perhaps `Mock` should own it's own DataMap and `NewMock` should add `in` to the datamap just on creation? This would actually reduce duplication a little, since each function wouldn't need to create its own datamap

File: expr/func_sortby_test.go [hunk 9]
```diff
@@ -301,29 +132,32 @@ func TestSortByMaxReverseLong(t *testing.T) {
...
-		if len(g.Datapoints) != len(exp.Datapoints) {
-			t.Fatalf("case %q: len output expected %d, got %d", name, len(exp.Datapoints), len(g.Datapoints))
-		}
-		for j, p := range g.Datapoints {
-			bothNaN := math.IsNaN(p.Val) && math.IsNaN(exp.Datapoints[j].Val)
-			if (bothNaN || p.Val == exp.Datapoints[j].Val) && p.Ts == exp.Datapoints[j].Ts {
-				continue
+
+	/*
+		TODO - Is sorting modification?
```
Comment (shanson7) [inline expr/func_sortby_test.go:148]: What is your opinion on this? I think it has to be, since 2 different branches could sort in 2 different ways and we wouldn't want them to clobber each other.

Comment (Dieterbe) [reply expr/func_sortby_test.go:148]: yeah. ordering may be implied, but relied upon in unpredictable ways.
let's sort into a new output slice, then we can enable this test.

**Comment by Dieterbe** [comment]
did you mean to drop 07590c176775b88e3af45a81b831bb18c542a521 ?

**Comment by shanson7** [comment]
> did you mean to drop 07590c1 ?

Nope, must not have pulled that in before rebasing.

File: expr/func_mock_test.go (hunk 5 above)
Comment (shanson7) [reply expr/func_mock_test.go:25]: @Dieterbe - what do you think of the above?

Comment (Dieterbe) [reply expr/func_mock_test.go:25]: i think the current version of this PR is too confusing because it's too subtley different from how the main codepath works. I think your suggestion is a slight improvement but i'm still not convinced it's worth making the testing code so different in architecture/flow just to optimize for LOC.
I think my preferred approach is to have the testing datamap work similarly to the real one, I doubt the extra LOC needed to manually add into the datamap first is an issue.

Comment (shanson7) [reply expr/func_mock_test.go:25]: It's not about LOC, it's about how painful it is to change all the tests if we decide to update how datamap works/is instantiated etc.

Comment (shanson7) [reply expr/func_mock_test.go:25]: Also, it helps enforce that all tests are doing the same (correct) thing

Comment (Dieterbe) [reply expr/func_mock_test.go:25]: OK then, let's give this a shot:

> Perhaps Mock should own it's own DataMap and NewMock should add in to the datamap just on creation?

Comment (shanson7) [reply expr/func_mock_test.go:25]: I'll look into if there is a good way to maintain what we have today without messing with Mock. Maybe another standalone function to init the datamap instead of the `make` line we use now?

Comment (shanson7) [reply expr/func_mock_test.go:25]: I think you are right that mock is not a good place for owning the datamap, since some tests need to create multiple Mocks (if they can take multiple seriesLists)
