### PR TITLE
only connect to peers that have non-null ip address. fix #683

### LINKED ISSUE #683: cluster looking up "null" and crashing
seen this on a prod instance, causing a few pod restarts. 
```
2017/07/10 13:08:45 [WARN] memberlist: Failed to resolve null: lookup null on 100.80.0.10:53: server misbehaving
2017/07/10 13:08:45 [cluster.go:81 Start()] [E] CLU Start: Failed to join cluster: 1 error(s) occurred:

* Failed to resolve null: lookup null on 100.80.0.10:53: server misbehaving

```

### PR DESCRIPTION
**Pull request by Dieterbe**
fix the problem seen in #683

### CODE REVIEW

File: scripts/k8s/entrypoint.sh [hunk 1]
```diff
@@ -56,9 +56,13 @@ if [ ! -z "$LABEL_SELECTOR" ]; then
 
 	_PODS=$(curl -s $CA -H "$AUTH" $PROTO://${HOST}:${PORT}/api/v1/namespaces/${POD_NAMESPACE}/pods?labelSelector=$LABEL_SELECTOR|jq .items[].status.podIP|sed -e "s/\"//g")
 	LIST=
+
 	for server in $_PODS; do
-	 LIST="${LIST}$server,"
+		if [ "$server" != "null" ] ; then
```
Comment (replay) [inline scripts/k8s/entrypoint.sh:61]: have we observed a situation where K8s returned `null` here? was that a pod which just recently got created and didn't have an IP assigned yet?

Comment (Dieterbe) [reply scripts/k8s/entrypoint.sh:61]: yes. i've seen this frequently. see #683

Comment (replay) [reply scripts/k8s/entrypoint.sh:61]: and this shouldn't be an issue, because once that pod comes up it will obtain the IPs of the others, connect to them and become a part of the memberlist cluster, right?

Comment (Dieterbe) [reply scripts/k8s/entrypoint.sh:61]: right
