### PR TITLE
don't issue requests that don't apply to query nodes, and if they do receive them, don't crash

### LINKED ISSUE #1293: /metrics/delete on query nodes: nilpointer in `api.(*Server).metricsDeleteLocal`
saw this using v0.11.0-259-g4c92934
```
[Macaron] 2019-04-25 13:25:18: Started POST /metrics/delete for 62.228.1.72
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb261ca]

goroutine 704 [running]:
github.com/grafana/metrictank/api.(*Server).metricsDeleteLocal(0xc00086e0c0, 0xc000001a3b, 0xc0004bca46, 0x17, 0x0, 0xc000068f70, 0x6aaf75)
        /go/src/github.com/grafana/metrictank/api/graphite.go:589 +0x2a
github.com/grafana/metrictank/api.(*Server).metricsDelete.func1(0xc00086e0c0, 0xc0004d0d40, 0xc0004bca46, 0x17, 0xc000144910, 0xc000474f00, 0xc000148a30)
        /go/src/github.com/grafana/metrictank/api/graphite.go:527 +0x69
created by github.com/grafana/metrictank/api.(*Server).metricsDelete
        /go/src/github.com/grafana/metrictank/api/graphite.go:526 +0x3ec
```

```
func (s *Server) metricsDeleteLocal(orgId uint32, query string) (int, error) {
        defs, err := s.MetricIndex.Delete(orgId, query)
        return len(defs), err
}
```
we need add nil checks on `s.MetricIndex` for query nodes, here and probably elsewhere too

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #1293 
tested with docker-cluster-query
```
curl -v -s -i http://localhost:6061/metrics/delete -d "query=foo.bar.*"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6061 (#0)
> POST /metrics/delete HTTP/1.1
> Host: localhost:6061
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 15
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Thu, 25 Apr 2019 19:19:15 GMT
Date: Thu, 25 Apr 2019 19:19:15 GMT
< Server: Caddy
Server: Caddy
< Trace-Id: 77f0002c62c7ce6a
Trace-Id: 77f0002c62c7ce6a
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Content-Length: 17
Content-Length: 17

< 
* Connection #0 to host localhost left intact
{"deletedDefs":0}* Closing connection 0
```
```
metrictank-q0_1  | [Macaron] 2019-04-25 19:19:15: Started POST /metrics/delete for 172.19.0.1
metrictank2_1    | [Macaron] 2019-04-25 19:19:15: Started POST /index/delete for 172.19.0.15
metrictank0_1    | [Macaron] 2019-04-25 19:19:15: Started POST /index/delete for 172.19.0.15
metrictank1_1    | [Macaron] 2019-04-25 19:19:15: Started POST /index/delete for 172.19.0.15
metrictank3_1    | [Macaron] 2019-04-25 19:19:15: Started POST /index/delete for 172.19.0.15
metrictank0_1    | [Macaron] 2019-04-25 19:19:15: Completed /index/delete 200 OK in 595.024µs
metrictank3_1    | [Macaron] 2019-04-25 19:19:15: Completed /index/delete 200 OK in 843.7µs
metrictank1_1    | [Macaron] 2019-04-25 19:19:15: Completed /index/delete 200 OK in 480.244µs
metrictank-q0_1  | [Macaron] 2019-04-25 19:19:15: Completed /metrics/delete 200 OK in 2.436699ms
metrictank2_1    | [Macaron] 2019-04-25 19:19:15: Completed /index/delete 200 OK in 753.214µs
```

```
curl -v -s -i http://localhost:6061/metrics/delete -d "query=some.id.of.a.metric.1*"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6061 (#0)
> POST /metrics/delete HTTP/1.1
> Host: localhost:6061
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 28
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: application/json
Content-Type: application/json
< Date: Thu, 25 Apr 2019 19:20:18 GMT
Date: Thu, 25 Apr 2019 19:20:18 GMT
< Server: Caddy
Server: Caddy
< Trace-Id: 372447439ff27ee9
Trace-Id: 372447439ff27ee9
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Content-Length: 19
Content-Length: 19

< 
* Connection #0 to host localhost left intact
{"deletedDefs":224}* Closing connection 0
```
```
metrictank-q0_1  | [Macaron] 2019-04-25 19:20:18: Started POST /metrics/delete for 172.19.0.1
metrictank3_1    | [Macaron] 2019-04-25 19:20:18: Started POST /index/delete for 172.19.0.15
metrictank0_1    | [Macaron] 2019-04-25 19:20:18: Started POST /index/delete for 172.19.0.15
metrictank2_1    | [Macaron] 2019-04-25 19:20:18: Started POST /index/delete for 172.19.0.15
metrictank1_1    | [Macaron] 2019-04-25 19:20:18: Started POST /index/delete for 172.19.0.15
metrictank1_1    | [Macaron] 2019-04-25 19:20:18: Completed /index/delete 200 OK in 36.641483ms
metrictank3_1    | [Macaron] 2019-04-25 19:20:18: Completed /index/delete 200 OK in 45.013004ms
metrictank2_1    | [Macaron] 2019-04-25 19:20:18: Completed /index/delete 200 OK in 47.188199ms
metrictank0_1    | [Macaron] 2019-04-25 19:20:18: Completed /index/delete 200 OK in 49.311407ms
metrictank-q0_1  | [Macaron] 2019-04-25 19:20:18: Completed /metrics/delete 200 OK in 51.236528ms
```

### CODE REVIEW

File: cluster/manager.go [hunk 1]
```diff
@@ -160,17 +160,21 @@ func (c *MemberlistManager) thisNode() HTTPNode {
...
-func (c *MemberlistManager) memberList() []HTTPNode {
+func (c *MemberlistManager) memberList(isReady, hasData bool) []HTTPNode {
 	c.RLock()
-	list := make([]HTTPNode, len(c.members), len(c.members))
-	i := 0
+	list := make([]HTTPNode, 0, len(c.members))
 	for _, p := range c.members {
-		list[i] = p
-		i++
+		if isReady && !p.IsReady() {
```
Comment (replay) [inline cluster/manager.go]: i've spent at least half a minute looking at those conditions to understand how they work, would be nice to have a comment there...

File: api/graphite.go [hunk 2]
```diff
@@ -1084,22 +1096,26 @@ func (s *Server) graphiteFunctions(ctx *middleware.Context) {
...
+	}
 
 	if !request.Propagate {
 		response.Write(ctx, response.NewJson(200, res, ""))
 		return
 	}
 
 	data := models.IndexTagDelSeries{OrgId: ctx.OrgId, Paths: request.Paths}
-	responses, err := s.peerQuery(ctx.Req.Context(), data, "clusterTagDelSeries,", "/index/tags/delSeries", true)
+	responses, err := s.peerQuery(ctx.Req.Context(), data, "clusterTagDelSeries,", "/index/tags/delSeries", true) // note: needlessl hits query nodes with no data, but can be cleaned later
```
Comment (replay) [inline api/graphite.go]: `needlessl + y`

File: api/graphite.go [hunk 3]
```diff
@@ -507,7 +513,7 @@ func findTreejson(query string, nodes []idx.Node) models.SeriesTree {
 }
 
 func (s *Server) metricsDelete(ctx *middleware.Context, req models.MetricsDelete) {
-	peers := cluster.Manager.MemberList()
+	peers := cluster.Manager.MemberList(false, true)
```
Comment (replay) [inline api/graphite.go]: if this calls a non-ready node, won't that node just respond with a bad error message and then this whole request results in a failure? or is this what we want because then the delete wasn't complete?

Comment (Dieterbe) [reply api/graphite.go]: Yeah we want to send to all nodes to make sure the request can be as complete as it can be.
it resulting in errors is a separate issue -> #1249

**Comment by robert-milan** [comment]
LGTM, aside from the one typo and those broken tests.

File: api/graphite.go (hunk 2 above)
Comment (woodsaj) [reply api/graphite.go]: This is the only call to s.peerQuery  We should just either update peerQuery to only call nodes that haveData
