### PR TITLE
correct Metricdef.LastUpdate when loading from persistent index

### LINKED ISSUE #1979: Stored 'lastupdate' being approximate can cause inconsistent missing data
**Describe the bug**

The cassandra idx has a configurable [update-interval](https://github.com/grafana/metrictank/blob/master/metrictank-sample.ini#L470). The `lastupdate` value is only updated when it gets out fo date by the configured `update-interval` (default `4h`). There is an equivalent in [bigtable](https://github.com/grafana/metrictank/blob/master/metrictank-sample.ini#L556) (default `3h`). 

The bug is that when a Metrictank instance restarts it will load in the `lastupdate` value from storage, which can be behind by as much `update-interval`. For series that are not regularly published, this means that there is a range of time that this series will not be returned, despite having data, because the `lastupdate` value is imprecise. 

#### 1. Reduce `update-interval`

This was our first step. It's effective at reducing the likelihood of the issue, but reducing it too much adds a decent amount of load onto Metrictank instances/cassandra. So diminishing returns on this work around.

#### 2. Periodically persist series in the index that haven't been persisted in a while and `lastupdate` is incorrect.

This seems like a reasonable solution since it would reduce the window that `lastupdate` is out-of-date in the database, but any instances that restart while it's out of date will not pick up changes afterward. Also, instances shutting down without updating `lastupdate` would not be able to update it later.

#### 3. Add `update-interval` seconds to `lastupdate` on startup.

This solution seems the most sound to me. If update interval is 60 minutes, add up to 3600 seconds to the `lastupdate`  we get from the database (not going beyond the current time) to err on the side of including series that might not have data rather than excluding series that might have data. 

**Helpful Information**
Metrictank Version: latest
Golang Version: 1.12
OS: RHEL

### PR DESCRIPTION
**Pull request by Dieterbe**
(instead of at previous fix, which did it at query time for Find(),
see https://github.com/grafana/metrictank/pull/1532)

This has two main benefits:
1) by making the change to the data, it works equally well across all
   types of queries, in particular this fixes the behavior for TagQuery
2) we no longer over-eagerly adjust the check at query time (if MT has
   seen a new point for a given metric - e.g. if the process has been up for
   a while - than the LastUpdate value in the memory index is perfectly
   accurate, and we don't need to make any adjustment)

fix #1979

### CODE REVIEW

File: idx/bigtable/bigtable.go [hunk 1]
```diff
@@ -300,6 +298,16 @@ func (b *BigtableIdx) LoadPartition(partition int32, defs []schema.MetricDefinit
 			return true
 		}
 		log.Debugf("bigtable-idx: found def %+v", def)
+
+		// because metricdefs get saved no more frequently than every updateInterval
+		// the lastUpdate field may be out of date by that amount (or more if the process
+		// struggled writing data. See updateBigtable() )
+		// To compensate, we set bump it here.  This should make sure to include all series
```
Comment (shanson7) [inline idx/bigtable/bigtable.go:305]:
```suggestion
		// To compensate, we bump it here.  This should make sure to include all series
```

File: idx/cassandra/cassandra.go [hunk 2]
```diff
@@ -377,15 +374,22 @@ func (c *CasIdx) load(defs []schema.MetricDefinition, iter cqlIterator, now time
...
+			Partition: partition,
+			Name:      name,
+			Interval:  interval,
+			Unit:      unit,
+			Mtype:     mtype,
+			Tags:      tags,
+			// because metricdefs get saved no more frequently than every updateInterval
+			// the lastUpdate field may be out of date by that amount (or more if the process
+			// struggled writing data. See updateCassandra() )
+			// To compensate, we set bump it here.  This should make sure to include all series
```
Comment (shanson7) [inline idx/cassandra/cassandra.go:388]:
```suggestion
			// To compensate, we bump it here.  This should make sure to include all series
```

**Review by shanson7 — APPROVED** [review]
Small comments on comments.

One interesting bit here is that all nodes should now have the same update interval (whether they are configured to update the index or not).

**Comment by shanson7** [comment]
Thanks for that quick turnaround! I know a couple of users that will be glad for this fix when we roll it out.
