### PR TITLE
fix bigtable idx pruning + index-rules.conf pruning for bigtable idx

### LINKED ISSUE #1108: index-rules.conf based pruning for bigtable
#924 was rebased on master but I forgot to apply the new mechanism to the bigtable idx plugin

### PR DESCRIPTION
**Pull request by Dieterbe**
fix bigtable idx pruning + index-rules.conf pruning for bigtable idx
    
    1) both the at-runtime pruning of the memory index, as well as the
       on-startup initialisation of the cassandra index group metrics by
       nameWithTags, whereas the on-startup init of the bigtable index
       did it by name.  So even if all defs for a.b;foo=bar are stale,
       bigtable idx wouldn't prune it if there's e.g.
       a non stale a.b;foo=quux, in contrast with cassandra and memory
       index which consider these separate series for pruning.
       We fix it here, and also clarify some things a bit, making
       the cassandra and bigtable index implementation on par and easily
       diffable.
    
    2) implement index-rules.conf based pruning for bigtable idx,
       rather than the old max-stale mechanism.
       fix #1108

### CODE REVIEW

File: idx/bigtable/bigtable.go [hunk 1]
```diff
@@ -493,10 +496,17 @@ func (b *BigtableIdx) deleteRow(key string) error {
 	return nil
 }
 
-func (b *BigtableIdx) Prune(oldest time.Time) ([]idx.Archive, error) {
-	pre := time.Now()
-	pruned, err := b.MemoryIdx.Prune(oldest)
-	statPruneDuration.Value(time.Since(pre))
+func (b *BigtableIdx) Prune(now time.Time) ([]idx.Archive, error) {
+	log.Info("bigtable-idx: start pruning of series")
```
Comment (woodsaj) [inline idx/bigtable/bigtable.go]: `bigtable-idx: starting prune of series` ?

Comment (Dieterbe) [reply idx/bigtable/bigtable.go]: same thing no?

**Comment by Dieterbe** [comment]
this doesn't break config because bigtable support hasn't been released yet
