### PR TITLE
Fix uneven length panics

### LINKED ISSUE #874: different-sized series causing panic in seriesaggregator
```
[Macaron] PANIC: runtime error: index out of range
/usr/local/go/src/runtime/panic.go:505 (0x42aea8)
/usr/local/go/src/runtime/panic.go:28 (0x429ced)
/go/src/github.com/grafana/metrictank/expr/seriesaggregators.go:122 (0xa02be4)
/go/src/github.com/grafana/metrictank/expr/func_aggregate.go:49 (0x9f296c)
/go/src/github.com/grafana/metrictank/expr/func_alias.go:28 (0x9f34b0)
/go/src/github.com/grafana/metrictank/expr/plan.go:220 (0xa020c3)
/go/src/github.com/grafana/metrictank/api/graphite.go:787 (0xa2d170)
/go/src/github.com/grafana/metrictank/api/graphite.go:277 (0xa27cd7)
/go/src/github.com/grafana/metrictank/api/routes.go:56 (0xa41884)
/usr/local/go/src/runtime/asm_amd64.s:576 (0x458774)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9a2bbe)
/go/src/github.com/grafana/metrictank/api/middleware/tracer.go:64 (0x9bf3aa)
/usr/local/go/src/runtime/asm_amd64.s:573 (0x4585aa)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9a2bbe)
/go/src/github.com/grafana/metrictank/api/middleware/stats.go:72 (0x9bebe8)
/usr/local/go/src/runtime/asm_amd64.s:573 (0x4585aa)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9a2bbe)
/go/src/github.com/grafana/metrictank/vendor/github.com/raintank/gziper/gzip.go:73 (0xa19557)
/usr/local/go/src/runtime/asm_amd64.s:573 (0x4585aa)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9a2bbe)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x9b2baa)
/usr/local/go/src/runtime/asm_amd64.s:573 (0x4585aa)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9a2bbe)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/logger.go:43 (0x9b1ef0)
/usr/local/go/src/runtime/asm_amd64.s:573 (0x4585aa)
/usr/local/go/src/reflect/value.go:447 (0x4b5bb8)
/usr/local/go/src/reflect/value.go:308 (0x4b5133)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x987fd4)
/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x987959)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9a2c7d)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:184 (0x9b3d51)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:286 (0x9ad83b)
/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x9a6a94)
/usr/local/go/src/net/http/server.go:2694 (0x6d641b)
/usr/local/go/src/net/http/server.go:1830 (0x6d2720)
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x45ad00)
[Macaron] 2018-03-16 10:04:17: Completed /render 500 Internal Server Error in 1.182240569s
```

### LINKED ISSUE #913: interval change resulting in unequal length series triggering panic in mergeSeries
similar to #761 but different.

I can reproduce like so:
```
./launch.sh docker-dev-custom-cfg-kafka
# run this for a minute or two
fakemetrics feed --period 30s --flush 30s --gnet-addr http://localhost:9000/metrics --gnet-key not_very_secret_key --mpo 30 --orgs 1
# then run this. will probably need to run several minutes before can repro
fakemetrics feed --period 120s --flush 120s --gnet-addr http://localhost:9000/metrics --gnet-key not_very_secret_key --mpo 120 --orgs 1
```

while running the 3rd command, issue this query in grafana:
`some.id.of.a.metric.1*` with timerange now-5min to now
this will make MT panic.
i added some debug info to MT like so (note, the comments andprint statements related to from/to were re diagnosing a different problem):
```
diff --git a/api/dataprocessor.go b/api/dataprocessor.go
index 5311e4d7..89f137cd 100644
--- a/api/dataprocessor.go
+++ b/api/dataprocessor.go
@@ -9,6 +9,7 @@ import (
 	"sync"
 	"time"
 
+	"github.com/davecgh/go-spew/spew"
 	"github.com/grafana/metrictank/api/models"
 	"github.com/grafana/metrictank/consolidation"
 	"github.com/grafana/metrictank/mdata"
@@ -138,6 +139,7 @@ func divide(pointsA, pointsB []schema.Point) []schema.Point {
 }
 
 func (s *Server) getTargets(ctx context.Context, reqs []models.Req) ([]models.Series, error) {
+	// from/to of the req here is same as plan, except if tweaked by function processing
 	// split reqs into local and remote.
 	localReqs := make([]models.Req, 0)
 	remoteReqs := make(map[string][]models.Req)
@@ -197,6 +199,8 @@ func (s *Server) getTargets(ctx context.Context, reqs []models.Req) ([]models.Se
 	return out, nil
 }
 
+// getTargetsRemote issues the requests on other nodes
+// it's nothing more than a thin network wrapper around getTargetsLocal of a peer.
 func (s *Server) getTargetsRemote(ctx context.Context, remoteReqs map[string][]models.Req) ([]models.Series, error) {
 	responses := make(chan getTargetsResp, len(remoteReqs))
 	rCtx, cancel := context.WithCancel(ctx)
@@ -609,6 +613,10 @@ func mergeSeries(in []models.Series) []models.Series {
 			log.Debug("DP mergeSeries: %s has multiple series.", series[0].Target)
 			for i := range series[0].Datapoints {
 				for j := 0; j < len(series); j++ {
+					if len(series[j].Datapoints) <= i {
+						spew.Dump(series)
+						panic("uneven length detected")
+					}
 					if !math.IsNaN(series[j].Datapoints[i].Val) {
 						series[0].Datapoints[i].Val = series[j].Datapoints[i].Val
 						break
@@ -659,9 +667,14 @@ func newRequestContext(ctx context.Context, req *models.Req, consolidator consol
 	// `from`   1..60 needs data    1..60   -> always adjust `from` to previous boundary+1 (here 1)
 	// `to`  181..240 needs data 121..180   -> always adjust `to`   to previous boundary+1 (here 181)
 
+	fmt.Println("Consol is", consolidator)
+
 	if consolidator == consolidation.None {
+		fmt.Println("consol None so:")
 		rc.From = prevBoundary(req.From, req.ArchInterval) + 1
 		rc.To = prevBoundary(req.To, req.ArchInterval) + 1
+		fmt.Println("from", req.From, "->", rc.From)
+		fmt.Println("to  ", req.To, "->", rc.To)
 		rc.AMKey = schema.AMKey{MKey: req.MKey}
 	} else {
 		rc.From = req.From
diff --git a/api/graphite.go b/api/graphite.go
index db690537..0403bc0b 100644
--- a/api/graphite.go
+++ b/api/graphite.go
@@ -674,6 +674,7 @@ func (s *Server) metricsDeleteRemote(ctx context.Context, orgId uint32, query st
 // note if you do something like sum(foo.*) and all of those metrics happen to be on another node,
 // we will collect all the indidividual series from the peer, and then sum here. that could be optimized
 func (s *Server) executePlan(ctx context.Context, orgId uint32, plan expr.Plan) ([]models.Series, error) {
+	// plan from/to are basically what user provided (but +1)
 
 	minFrom := uint32(math.MaxUint32)
 	var maxTo uint32
```

and got the following output:
(while fakemetrics was flushing at xx:15s every 2min)
```
metrictank_1    | [Macaron] 2018-05-17 10:23:12: Started POST /render for 172.19.0.1, 172.19.0.1, 172.19.0.2
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | consol None so:
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | Consol is NoneConsolidator
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552521
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | consol None so:
metrictank_1    | from 1526552293 -> 1526552281
metrictank_1    | to   1526552593 -> 1526552581
metrictank_1    | ([]models.Series) (len=2 cap=2) {
metrictank_1    |  (models.Series) {
metrictank_1    |   Target: (string) (len=37) "some.id.of.a.metric.12;id=12;some=tag",
metrictank_1    |   Datapoints: ([]schema.Point) (len=3 cap=10) {
metrictank_1    |    (schema.Point) {
metrictank_1    |     Val: (float64) 7.418930526012729,
metrictank_1    |     Ts: (uint32) 1526552400
metrictank_1    |    },
metrictank_1    |    (schema.Point) {
metrictank_1    |     Val: (float64) 9.763679531881163,
metrictank_1    |     Ts: (uint32) 1526552520
metrictank_1    |    },
metrictank_1    |    (schema.Point) {
metrictank_1    |     Val: (float64) NaN,
metrictank_1    |     Ts: (uint32) 1526552640
metrictank_1    |    }
metrictank_1    |   },
metrictank_1    |   Tags: (map[string]string) <nil>,
metrictank_1    |   Interval: (uint32) 120,
metrictank_1    |   QueryPatt: (string) (len=22) "some.id.of.a.metric.1*",
metrictank_1    |   QueryFrom: (uint32) 1526552293,
metrictank_1    |   QueryTo: (uint32) 1526552593,
metrictank_1    |   QueryCons: (consolidation.Consolidator) NoneConsolidator,
metrictank_1    |   Consolidator: (consolidation.Consolidator) AverageConsolidator
metrictank_1    |  },
metrictank_1    |  (models.Series) {
metrictank_1    |   Target: (string) (len=37) "some.id.of.a.metric.12;id=12;some=tag",
metrictank_1    |   Datapoints: ([]schema.Point) (len=2 cap=2) {
metrictank_1    |    (schema.Point) {
metrictank_1    |     Val: (float64) NaN,
metrictank_1    |     Ts: (uint32) 1526552400
metrictank_1    |    },
metrictank_1    |    (schema.Point) {
metrictank_1    |     Val: (float64) 9.763679531881163,
metrictank_1    |     Ts: (uint32) 1526552520
metrictank_1    |    }
metrictank_1    |   },
metrictank_1    |   Tags: (map[string]string) <nil>,
metrictank_1    |   Interval: (uint32) 120,
metrictank_1    |   QueryPatt: (string) (len=22) "some.id.of.a.metric.1*",
metrictank_1    |   QueryFrom: (uint32) 1526552293,
metrictank_1    |   QueryTo: (uint32) 1526552593,
metrictank_1    |   QueryCons: (consolidation.Consolidator) NoneConsolidator,
metrictank_1    |   Consolidator: (consolidation.Consolidator) AverageConsolidator
metrictank_1    |  }
metrictank_1    | }
metrictank_1    | [Macaron] PANIC: uneven length detected
metrictank_1    | /usr/lib/go/src/runtime/panic.go:502 (0x42a7a8)
grafana_1       | t=2018-05-17T10:23:12+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/3/render status=500 remote_addr=172.19.0.1 time_ms=12 size=5459 referer="http://localhost:3000/d/zFTgAw7mk/fake-metrics-data?orgId=1&from=now-5m&to=now"
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/dataprocessor.go:618 (0xa7554f)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/graphite.go:772 (0xa7d7f4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/graphite.go:278 (0xa78705)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/routes.go:56 (0xa92284)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:576 (0x457b34)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9f219e)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/middleware/tracer.go:64 (0xa0e99a)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:573 (0x45796a)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9f219e)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/api/middleware/stats.go:72 (0xa0e1d8)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:573 (0x45796a)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9f219e)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/raintank/gziper/gzip.go:73 (0xa69bb7)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:573 (0x45796a)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9f219e)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/recovery.go:161 (0xa0218a)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:573 (0x45796a)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x9f219e)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/logger.go:43 (0xa014d0)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:573 (0x45796a)
metrictank_1    | /usr/lib/go/src/reflect/value.go:447 (0x4b5008)
metrictank_1    | /usr/lib/go/src/reflect/value.go:308 (0x4b4583)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9d75b4)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9d6f39)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x9f225d)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:184 (0xa03331)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:286 (0x9fce1b)
metrictank_1    | /home/dieter/go/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x9f6074)
metrictank_1    | /usr/lib/go/src/net/http/server.go:2694 (0x6d67cb)
metrictank_1    | /usr/lib/go/src/net/http/server.go:1830 (0x6d2ad0)
metrictank_1    | /usr/lib/go/src/runtime/asm_amd64.s:2361 (0x459fb0)
metrictank_1    | [Macaron] 2018-05-17 10:23:12: Completed /render 500 Internal Server Error in 3.655613ms
```

### LINKED ISSUE #1095: Panic when merging series
The code on https://github.com/grafana/metrictank/blob/master/api/dataprocessor.go#L624 assumes when merging series that they all have the same number of data points.  If that is not true, then it can panic for "runtime error: index out of range"

### PR DESCRIPTION
**Pull request by Dieterbe**
Document concepts better and in particular introduce new concept of a "canonical series".
Now we massage the fetch and fix parameters such that a high resolution series will always look like a native lower resolution serie (one that has the same interval as what we're normalizing to).
In particular, they will now have corresponding timestamps, and the same amount of points.

fix #913  (panic in mergeSeries) - tried the repro case. can't repro anymore.
fix #1095 (mergeSeries and sumSeries) - can not repo either one with this code.
fix #874 (dupe)

### CODE REVIEW

**Comment by Dieterbe** [comment]
note to self, this patch was helpful to see what's going on

```
diff --git a/api/dataprocessor.go b/api/dataprocessor.go
index ff460aea..0ca7042a 100644
--- a/api/dataprocessor.go
+++ b/api/dataprocessor.go
@@ -9,6 +9,7 @@ import (
        "sync"
        "time"
 
+       "github.com/davecgh/go-spew/spew"
        "github.com/grafana/metrictank/api/models"
        "github.com/grafana/metrictank/consolidation"
        "github.com/grafana/metrictank/mdata"
@@ -647,6 +648,19 @@ func mergeSeries(in []models.Series) []models.Series {
        }
        merged := make([]models.Series, len(seriesByTarget))
        i := 0
+       for seg, series := range seriesByTarget {
+               fmt.Printf("mergeSeries  %v - len %d\n", seg, len(series))
+               lens := make(map[int]int)
+               for _, serie := range series {
+                       l := len(serie.Datapoints)
+                       fmt.Println("len points", l)
+                       lens[l] = l
+               }
+               if len(lens) > 1 {
+                       log.Error("mergeSeries detected merge of series of unequal length")
+                       spew.Dump(series)
+               }
+       }
```

File: util/overflow.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package util
+
+import "math"
+
+func Adduint32(a, b uint32) uint32 {
+	if a > math.MaxInt32-b {
```
Comment (Dieterbe) [inline util/overflow.go]: should be math.MaxUint32 ?

**Comment by Dieterbe** [comment]
should also fix #761
