### PR TITLE
Fix summarize function

### LINKED ISSUE #903: summarize function returning incorrect results
If i send a request for 3months of data, summarized into 30day averages
```
target: summarize(metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32, '30day', 'avg', false)
from: 1517414400
until: 1525104059
format: json
```

i get back 
```
[  
  {  
    "target":"summarize(metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32, \"30day\", \"avg\")",
    "tags":{  
      "name":"metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32",
      "summarize":"30day",
      "summarizeFunction":"avg"
    },
    "datapoints":[  
      [  
        66.50059255122777,
        1516320000
      ]
    ]
  }
]
```
As well as there being only 1 datapoint returned instead of the expected 3, the timestamp of the returned datapoint is for 12days before the requested From.

If a add a keepLastValue() function to the query, forcing the query to be handed off to Graphite, i get the correct results.

This looks to be a fairly recent bug, as a number of queries that were working last month are not working today.

### PR DESCRIPTION
**Pull request by shanson7**
Fixes #903

### CODE REVIEW

File: expr/func_summarize_test.go [hunk 1]
```diff
@@ -665,6 +665,78 @@ func TestSummarizeAlignToFrom(t *testing.T) {
 	testSummarize("AlignToFrom", input, outputMax[1], "45s", "max", true, t)
 }
 
+func TestSummarizeLargeIntervalTimestamps(t *testing.T) {
+
+	// This test is specifically testing the timestamp behavior, so we don't need real values.
+	// However, we do need a lot of datapoints to trigger the bug we are regression testing against.
+	interval1Day := uint32(24 * 60 * 60)
+	numTimestamps := uint32(2000)
```
Comment (Dieterbe) [inline expr/func_summarize_test.go]: where does the 2000 come from? is the goal to test 2000 days?

File: expr/func_summarize_test.go [hunk 2]
```diff
@@ -665,6 +665,78 @@ func TestSummarizeAlignToFrom(t *testing.T) {
...
+	}
+
+	outputInterval := 365 * interval1Day
+
+	var unaligned365dsum = []schema.Point{
+		{Val: 0, Ts: 1450656000},
+		{Val: 0, Ts: 1482192000},
+		{Val: 0, Ts: 1513728000},
+		{Val: 0, Ts: 1545264000},
+		{Val: 0, Ts: 1576800000},
```
Comment (Dieterbe) [inline expr/func_summarize_test.go]: what's the relation between these ts? can they be set from code so it's more obvious?

File: expr/func_summarize_test.go [hunk 3]
```diff
@@ -665,6 +665,78 @@ func TestSummarizeAlignToFrom(t *testing.T) {
...
+		{Val: 0, Ts: 1608336000},
+	}
+
+	var aligned365dsum = []schema.Point{
+		{Val: 0, Ts: 1464637518},
+		{Val: 0, Ts: 1496173518},
+		{Val: 0, Ts: 1527709518},
+		{Val: 0, Ts: 1559245518},
+		{Val: 0, Ts: 1590781518},
+		{Val: 0, Ts: 1622317518},
```
Comment (Dieterbe) [inline expr/func_summarize_test.go]: what's the relation between these ts? can they be set from code so it's more obvious?

File: expr/func_summarize_test.go [hunk 4]
```diff
@@ -665,6 +665,78 @@ func TestSummarizeAlignToFrom(t *testing.T) {
...
+			QueryTo:    endTime,
+			Interval:   outputInterval,
+			Datapoints: getCopy(inputDps),
+		},
+	}
+	outputSum := [][]models.Series{
+		{
+			{
+				Target:     "summarize(align, \"365d\", \"sum\")",
+				QueryPatt:  "summarize(align, \"365d\", \"sum\")",
```
Comment (Dieterbe) [inline expr/func_summarize_test.go]: any particular reason we're testing with 365d buckets?
i would suggest to target the bugreport specifically and use 30d buckets , and a from-until range as used in the ticket of 89.000683 days, as well as a few different values like 89 days, 90 days, etc

File: expr/func_summarize_test.go (hunk 2 above)
Comment (shanson7) [reply expr/func_summarize_test.go]: These are the expected outcome. Setting from code would be partially duplicating the logic in the function under test, which I try to avoid in test code.

Comment (shanson7) [reply expr/func_summarize_test.go]: (These are the results as graphite reported them)

File: expr/func_summarize_test.go (hunk 1 above)
Comment (shanson7) [reply expr/func_summarize_test.go]: The bug in this case was two-fold. 

1. start-end caused an underflow for uint32
2. Division was by the interval, rather than the step (as it is in the python code) as well as using the adjusted start, end (rather than the original).

So, the bug comes about when (start-end) / interval is *less than* the number of input datapoints.

I needed a large enough number of input datapoints, and a large enough interval such that that `len(input) >  (start-end) / interval` (taking into account underflow). These were arbitrary numbers that I selected that caused the above to be true.

File: expr/func_summarize_test.go (hunk 4 above)
Comment (shanson7) [reply expr/func_summarize_test.go]: The bug is also dependent on the input datapoints. That wasn't specified in the bug report, but I don't believe it's necessary to exactly reproduce as in the bug report. I expect that I could though, if you wish.

**Comment by shanson7** [comment]
I modified the time range to better match the issue report (assuming a 1 hour input interval). It still exhibits the bug with the old code, and is fixed with the new code.

**Comment by Dieterbe** [comment]
great, thanks Sean. will check it out and get back to you.

File: expr/func_summarize_test.go [hunk 5]
```diff
@@ -665,6 +665,73 @@ func TestSummarizeAlignToFrom(t *testing.T) {
...
+		{Val: 0, Ts: 1469821518},
+	}
+
+	input := []models.Series{
+		{
+			Target:     "align",
+			QueryPatt:  "align",
+			QueryFrom:  startTime,
+			QueryTo:    endTime,
+			Interval:   outputInterval,
```
Comment (Dieterbe) [inline expr/func_summarize_test.go]: shouldn't this be inputInterval?

**Comment by Dieterbe** [comment]
generally for bugfixes i recommend first commit = test case, 2nd = bugfix.
that makes it easy to verify. now the burden is on the reviewer (or any time a future reader wants to verify the solution) to manually undo the fix to confirm the old code doesn't pass the test case.
(`git add -p` and `git rebase -i` make it easy to structure the commit history this way, if needed)

File: expr/func_summarize_test.go (hunk 2 above)
Comment (Dieterbe) [reply expr/func_summarize_test.go]: i agree we shouldn't use advanced code that is similar to or shared with the code under test,
but now this is pretty unreadable: i have to pull out a calculator to find out they are apart by 2592000 , aka 30*24*3600, and to confirm that the first ts is the last interval boundary before the startTime.
I think trivial, obviously-correct solves this problem. Thus I would recommend something like:

```
   start := startTime - (startTime % outputInterval)
        var unalignedExpected = []schema.Point{
                {Val: 0, Ts: start},
                {Val: 0, Ts: start + outputInterval},
                {Val: 0, Ts: start + 2*outputInterval},
                {Val: 0, Ts: start + 3*outputInterval},
        }

```

File: expr/func_summarize_test.go (hunk 4 above)
Comment (Dieterbe) [reply expr/func_summarize_test.go]: FWIW the data from the bug report has interval=10s

**Comment by Dieterbe** [comment]
> I modified the time range to better match the issue report (assuming a 1 hour input interval). It still exhibits the bug with the old code, and is fixed with the new code.

note that in the bug, there's only 1 returned output point, whereas running the test on the broken code results in:
```
go test -run=TestSummarizeLargeIntervalTimestamps
--- FAIL: TestSummarizeLargeIntervalTimestamps (0.00s)
	func_summarize_test.go:759: case "LongIntervals" ("30d", "sum", false): len output expected [{0 1464480000} {0 1467072000} {0 1469664000} {0 1472256000}], got [{0 1464480000} {0 1467072000} {0 1469664000}]
FAIL
exit status 1
FAIL	github.com/grafana/metrictank/expr	0.004s
```

but, good news!
when i change the test to use input resolution of 10s I get:
```
go test -run=TestSummarizeLargeIntervalTimestamps
--- FAIL: TestSummarizeLargeIntervalTimestamps (0.01s)
	func_summarize_test.go:759: case "LongIntervals" ("30d", "sum", false): len output expected [{0 1464480000} {0 1467072000} {0 1469664000} {0 1472256000}], got [{0 1464480000}]
FAIL
exit status 1
FAIL	github.com/grafana/metrictank/expr	0.015s
```

**Comment by shanson7** [comment]
I restructured the commits to split out the test, fix and orthogonal changes. 

In the test, I now compute the output timestamps using the expected interval. I also changed the input interval to `10s`.

**Comment by Dieterbe** [comment]
we have a winner! now go enjoy monitorama!
