### PR TITLE
leverage in-flight requests of other replicas to possibly overcome shard query errors

### LINKED ISSUE #1817: Speculative query failure causes request failure
While querying peers, if one of the peer requests fails MT [checks](https://github.com/grafana/metrictank/blob/c2c86e493cc523b53de44aa7a21f91d05e9ea534/api/cluster.go#L602) if there are other peers in that shard, and if so, will try that peer. However, if speculative execution has already kicked off there may be no peer left and the request will fail. However, there may still be an in-flight request that hasn't failed (original or speculative). The request shouldn't be failed unless there are also no in-flight requests left. 

We saw this when our speculative query failed with a 503 and the request was immediately failed, despite the original peer still possibly able to respond successfully.

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #1817 

one interesting case is what happens when an error comes in, and there are more replicas available for querying, as well as a request in flight (you can have this with replicas >= 3)

we could do two things here:
1) wait until the in-flight response comes in, and only when an error comes back for it, try the 3rd replica
2) initiate request to 3rd replica, resulting in 2 in flight requests (and a total of 3 for the given shard)

I've opted for number 2.

### CODE REVIEW

File: api/cluster.go [hunk 1]
```diff
@@ -621,31 +643,22 @@ func queryPeers(ctx context.Context, peerGroups map[int32][]cluster.Node, name s
 
 			case <-tickChan:
 				// Check if it's time to speculate!
-				percentReceived := float64(len(receivedResponses)) / float64(len(peerGroups))
-				if percentReceived >= speculationThreshold {
+				ratioReceived := float64(len(receivedResponses)) / float64(len(peerGroups))
```
Comment (shanson7) [inline api/cluster.go:646]: To be completely pedantic, percentage *is* a ratio. I like it here since it implies a clear relationship with the `speculationThreshold` though it may be confusing since it is represented as `[0-1]` rather than `[0-100]`, but I don't think ratio makes that any clearer.

Comment (Dieterbe) [reply api/cluster.go:646]: seems like this can be argued both ways. taking the path of least resistance..
