### PR TITLE
Fix crashing when non-configured consolidation function used

### LINKED ISSUE #835: Metrictank crashes when asking for an aggregation that doesn't exist
For an aggregation configured to only compute `min` rollups, if a user asks for `avg` metrictank crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99bab4]
goroutine 344721736 [running]:
github.com/grafana/metrictank/api.doRecover(0xc5c88d1e48)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:29 +0x256
panic(0xbdd9a0, 0x115b350)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/grafana/metrictank/mdata.(*AggMetric).Get(0x0, 0x5a6cbee65a4531e6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/mdata/aggmetric.go:177 +0xb4
github.com/grafana/metrictank/mdata.(*AggMetric).GetAggregated(0xc48b9146e0, 0x2, 0x5a4531e600000e10, 0x5a6cbee6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/mdata/aggmetric.go:158 +0xea
github.com/grafana/metrictank/api.(*Server).getSeriesAggMetrics(0xc420782000, 0xc4e86c0550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:483 +0x1c1
github.com/grafana/metrictank/api.(*Server).getSeries(0xc420782000, 0xc4e86c0550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:416 +0x7b
github.com/grafana/metrictank/api.(*Server).getSeriesFixed(0xc420782000, 0x1129400, 0xc8671ef980, 0xc5c4065c50, 0x22, 0xc7250dae60, 0x91, 0xc4ad331560, 0x85, 0x5a6cbee65a4531e6, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:401 +0x132
github.com/grafana/metrictank/api.(*Server).getTarget(0xc420782000, 0x1129400, 0xc8671ef980, 0xc5c4065c50, 0x22, 0xc7250dae60, 0x91, 0xc4ad331560, 0x85, 0x5a6cbee65a4531e6, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:340 +0x717
github.com/grafana/metrictank/api.(*Server).getTargetsLocal.func1(0x1129340, 0xc5e567aa00, 0xc420782000, 0xc5a7d39520, 0xc4ab8d8600, 0xc6bfe65880, 0xc448a6e660, 0xc5c4065c50, 0x22, 0xc7250dae60, ...)
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:274 +0x162
created by github.com/grafana/metrictank/api.(*Server).getTargetsLocal
	/Users/shanson7/Code/metrictank_notagsintree/src/github.com/grafana/metrictank/api/dataprocessor.go:270 +0x2bd
```

### PR DESCRIPTION
**Pull request by shanson7**
Fixes #835

### CODE REVIEW

File: mdata/aggmetric.go [hunk 1]
```diff
@@ -137,27 +137,33 @@ func (a *AggMetric) getChunk(pos int) *chunk.Chunk {
...
-				return a.minMetric.Get(from, to)
+				agg = a.minMetric
 			case consolidation.Max:
-				return a.maxMetric.Get(from, to)
+				agg = a.maxMetric
 			case consolidation.Sum:
-				return a.sumMetric.Get(from, to)
+				agg = a.sumMetric
+			default:
+				panic(fmt.Sprintf("AggMetric.GetAggregated(): unknown consolidator %q", consolidator))
```
Comment (DanCech) [inline mdata/aggmetric.go]: Shouldn't this case be removed?

Comment (shanson7) [reply mdata/aggmetric.go]: Not necessarily. While it can be handled below, it is a valid (and separate) issue that unexpected values got passed in here.

Comment (DanCech) [reply mdata/aggmetric.go]: Aha, I wasn't thinking about `agg` getting set to a nil value above.  In any case, I'd be very keen to see the `panic` calls converted to error returns unless there's a compelling reason not to.

Comment (shanson7) [reply mdata/aggmetric.go]: That's fair. I wasn't sure if panics got treated differently than errors, but (aside from runtime error panics) they both get turned into `500` responses. Ideally, a `400` would return from some of these.

Comment (Dieterbe) [reply mdata/aggmetric.go]: note: the "automatic turning panics into http 500 responses" only works when the recover happens (the macaron middleware) in the same goroutine as the panic. in this case not, because we spawn new goroutines for all s.getTargetsLocal calls. (there's one or two other open tickets describing running into this.. unpleasantery. needless to say, significant problem that we need to resolve)

regarding when (not) to panic, we have a policy for that now : https://github.com/grafana/metrictank/blob/master/docs/CONTRIBUTING#L19
if the articulation needs revising, please do tell :)

for this PR, you don't need to worry about cleaning up panics that were already there, we can do that later. (though you're welcome to)

Comment (shanson7) [reply mdata/aggmetric.go]: I switched the panics to errors, but I'm not sure at what granularity we need the metrics to be posted. There could be a metric per, or just a generic "GetAggregated" error. I'm also not sure of the naming convention, since the memory index does "idx.memory" and ccache does "cache.metric"

**Comment by Dieterbe** [comment]
i added commit 1621a55ee389bec18af8f2c5ba36eb49204212ca which should clarify the error handling & recovered_errors metrics. github didn't let me create a new PR because this one already exists (never mind that i couldn't push to it).
anyway i merged it to master.
