### PR TITLE
Fix issue 1740

### LINKED ISSUE #1740: panic when a peer is temporarily unavailable
We've seen multiple instances of an MT panicking when it got queried while some of its peers were temporarily unavailable. This is one of the messages I saw:

```
2020-03-31 21:30:57.829 [INFO] Proxying to Graphite because of error: unknown function "groupByNode"
2020/03/31 21:30:57 [WARN] memberlist: Was able to connect to <pod name> but other probes failed, network may be misconfigured
2020/03/31 21:30:58 [DEBUG] memberlist: Failed ping: <pod name> (timeout reached)
panic: runtime error: index out of range

goroutine 2765795 [running]:
github.com/grafana/metrictank/api.queryPeers.func1(0xc0317d6660, 0xc02898c480, 0x117d600, 0xc0025e80c0, 0xc0006d25a0, 0xc0006fc560)
        /go/src/github.com/grafana/metrictank/api/cluster.go:559 +0xd20
created by github.com/grafana/metrictank/api.queryPeers
        /go/src/github.com/grafana/metrictank/api/cluster.go:526 +0xb1
```

The running version was `v0.13.1-458-ged6257f`. 

Probably the code shouldn't assume that each group has at least one ready member here: https://github.com/grafana/metrictank/blob/bdd9d1e4de447e11633ba53ee557fbcb5ffe470e/api/cluster.go#L559

### PR DESCRIPTION
**Pull request by replay**
this changes 2 things:
1) it prevents that an empty slice of peers gets passed into `queryPeers()`
2) it makes `queryPeers()` handle an empty slice of peers better, if for an unknown reason this still happens

fixes #1740

### CODE REVIEW

File: api/cluster.go [hunk 1]
```diff
@@ -563,6 +563,12 @@ func queryPeers(ctx context.Context, peerGroups map[int32][]cluster.Node, name s
 		}
 
 		for group, peers := range peerGroups {
+			if len(peers) == 0 {
+				errorChan <- fmt.Errorf("peer group %d has no peers", group)
```
Comment (shanson7) [inline api/cluster.go:567]: errorChan is a buffered chan of size 1. If we send to it here and continue, we have the chance of blocking on the channel [here](https://github.com/grafana/metrictank/pull/1747/files#diff-bc8a656be21edce0cf2a74adf23d7aeaR614). Since the common approach taken by callers is to consume all responses, then consume the errorChan, that could be a deadlock.

Also, if this is supposed to be an ignorable error (since we continue processing) maybe it should just be logged? There is no good way for a caller to know to ignore this error vs propagating it.

Comment (replay) [reply api/cluster.go:567]: right, good catch! i'll just log it

File: api/cluster.go [hunk 2]
```diff
@@ -563,6 +563,12 @@ func queryPeers(ctx context.Context, peerGroups map[int32][]cluster.Node, name s
 		}
 
 		for group, peers := range peerGroups {
+			if len(peers) == 0 {
+				log.Warningf("Peer group %d has no peers", group)
```
Comment (Dieterbe) [inline api/cluster.go:567]: logs should always have a prefix
```
api/cluster.go
378:		log.Errorf("HTTP getData() %s", err.Error())
426:	log.Debugf("HTTP %s across %d instances", name, len(peers)-1)
443:			log.Debugf("HTTP Render querying %s%s", peer.GetName(), path)
447:				log.Errorf("HTTP Render error querying %s%s: %q", peer.GetName(), path, err.Error())
509:		log.Errorf("HTTP peerQuery unable to get peers, %s", err.Error())
551:			//log.Debugf("HTTP Render querying %s%s", peer.GetName(), path)
560:				log.Errorf("Peer %s responded with error = %q", peer.GetName(), err.Error())
567:				log.Warningf("Peer group %d has no peers", group)
659:				log.Warnf("Something weird: %v", originalPeers)

```

Comment (replay) [reply api/cluster.go:567]: sorry, i'm not completely sure how to understand your message. usually our prefix is just `functionName:` right? do you mean to say that I should update all of those log statements in this PR?

Comment (Dieterbe) [reply api/cluster.go:567]: just put "HTTP " as prefix in your log messages. don't worry about consistency across the entire codebase
