### PR TITLE
Replaced Macaron logger with custom logger enabling query statistics

### LINKED ISSUE #1538: Implement Metrictank query logging
This is the current plan:

Query Logging in Metrictank

Goals to consider:
We have often encountered situations where a user was overloading their metrictank cluster with queries, and we saw that the issues were caused by their queries, but we didn’t know what the exact queries were. When we tell a customer that their queries are overloading their instance, the first question often is “which query”. So we need logging that allows us to answer this question for them and for ourselves
We want to analyze which metrics are getting queried by customers, so we need to log the queries in order to then analyze them and extract the metric names.
The resulting utility will be closed source, so it must not be in the Metrictank repo

What needs to be logged
Trace id. This allows us to correlate logs across multiple mt instances
OrgId. We need this for multi-tenant clusters so we know who made the request
Query params: Everything in the request payload. targets, maxDatapoints, etc...
Referrer: Super useful to track down where bad requests are coming from.
Source ip: From x-forwarded-for header if there is one, otherwise the actual source IP
Status code
Request timing info: How long the request took to complete
Error messages: If the request was not 2xx, we should include the error message for why it failed.

Log Format
We need a specific prefix based on which we can filter these new query log lines, this will allow us to directly label them in promtail and enable efficient querying.
We’re going to URL encode all the request params and headers into a string, in a similar fashion to what Loki and Cortex are doing:

query: ip=? orgID=? sourceIp=? status=? duration=? traceID=? request=”?” headers=”?” duration=? error=“?”

In error / traceId all “ characters get replaced by ‘ for parsability of the log format.
The value of request is a url encoded string containing all the request params.
The value of headers is also a url encoded string with the received headers & values, but before logging them we will filter them by a configurable blacklist to remove authentication headers etc

### PR DESCRIPTION
**Pull request by fkaleo**
Disabled Macaron logger. Replaced with a custom logger that only logs errors and render queries. Query information is embedded to enable useful statistics, such as the query, orgID, sourceIP, etc.  

Example log:
`ts=2020-01-27T11:03:23.961343521Z traceID=49a071d27275ff00 msg="POST /render?format=json&from=-6h&maxDataPoints=413&target=aliasByNode%28metrictank.stats.docker-env.default.%2A.metrics_active.gauge32%2C+3%2C4%29&until=now (200) 81.505189ms" orgID=1 sourceIP="172.21.0.1"`

Fixes #1538

### CODE REVIEW

**Comment by Dieterbe** [comment]
does it log the parameters too if they came in as POST fields?

File: api/middleware/logger.go [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+	return rw.ResponseWriter.Write(b)
+}
+
+func Logger() macaron.Handler {
+	return func(ctx *Context) {
+		start := time.Now()
+		ctx.Resp = &LoggingResponseWriter{
+			ResponseWriter: ctx.Resp,
+		}
+		rw := ctx.Resp.(*LoggingResponseWriter)
```
Comment (replay) [inline api/middleware/logger.go]: instead of directly assigning `&LoggingResponseWriter{...` to `ctx.Resp` and then having to type assert, wouldn't it be nicer to initialize that into a variable which then gets assigned into `ctx.Resp` like 

```
rw = LoggingResponseWriter{
			ResponseWriter: ctx.Resp,
		}
ctx.Resp = &rw
```

Not sure if that's just me, but if possible I prefer to avoid type assertions.

**Comment by replay** [comment]
We have instances which receive `>=300` requests on `/render` per second, so i think it's worth it to try to save allocations in this logging logic. There are currently a lot of temporary string variables getting allocated which then get concatenated into the logline if they're `!=""`, you could use something like `strings.Builder` and just directly write those string values and then pool them in a `sync.Pool` to reduce the number of allocations.

File: api/middleware/logger.go [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+				content += fmt.Sprintf(" headers=\"%s\"", string(headers))
+			}
+		}
+
+		log.Println(colorLog(rw.Status(), content))
+	}
+}
+
+func colorLog(statusCode int, log string) string {
+	if statusCode >= 200 && statusCode <= 202 {
```
Comment (replay) [inline api/middleware/logger.go]: shouldn't all `2xx` get the same color

Comment (Dieterbe) [reply api/middleware/logger.go]: color? we don't want colored logs?

**Comment by fkaleo** [comment]
> does it log the parameters too if they came in as POST fields?

yes it does, it transforms them into URL parameters

File: api/middleware/logger.go [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+		err := ctx.Req.ParseForm()
+		if err != nil {
+			log.Errorf("Could not parse http request: %v", err)
+		}
+		paramsAsString := ""
+		if len(ctx.Req.Form) > 0 {
+			paramsAsString += "?"
+			paramsAsString += ctx.Req.Form.Encode()
+		}
+		content += fmt.Sprintf(" msg=\"%s %s%s (%v) %v\" orgID=%d", ctx.Req.Method, ctx.Req.URL.Path, paramsAsString, rw.Status(), time.Since(start), ctx.OrgId)
```
Comment (woodsaj) [inline api/middleware/logger.go]: I feel that the statuscode and request duration should be named fields in the log, rather then being put in 'msg'.  Also, is I feel that 'request' would be a better field name than 'msg'

Comment (fkaleo) [reply api/middleware/logger.go]: I agree. I did it that way to copy Cortex's way.

File: api/middleware/logger.go (hunk 2 above)
Comment (replay) [reply api/middleware/logger.go]: Doesn't hurt to have colors... I don't think the colors would matter much for us, especially not looking at the logs in Loki because I suspect that the colors won't be visible there. But when considering how to increase Metrictank adoption I think colored logs might make a better first impression when somebody looks at MT for the first time.

Comment (woodsaj) [reply api/middleware/logger.go]: dont add colors. 

Most logging frameworks only use colors when they detect that the logs are being written to a terminal, because only terminals know how to show colors.    If you add the control characters when outputing to destinations that dont support terminal control colors, the control characters are just rendered as text and make the log lines hard to read.

Comment (replay) [reply api/middleware/logger.go]: I wonder how that's going to look in Loki? is it going to show these control characters? if so then it would be better if there's at least the option to disable the coloring.

Comment (fkaleo) [reply api/middleware/logger.go]: > Doesn't hurt to have colors... I don't think the colors would matter much for us, especially not looking at the logs in Loki because I suspect that the colors won't be visible there. But when considering how to increase Metrictank adoption I think colored logs might make a better first impression when somebody looks at MT for the first time.

Grafana renders colors when pulling logs from Loki.

File: api/middleware/logger.go (hunk 1 above)
Comment (fkaleo) [reply api/middleware/logger.go]: Thanks! Fixed in 3e51444

File: api/middleware/logger.go (hunk 2 above)
Comment (fkaleo) [reply api/middleware/logger.go]: Removed color logging in d979e98

Comment (Dieterbe) [reply api/middleware/logger.go]: And how does it know what color to use? I would hope it does this by looking at labels or the log level, rather then by looking for terminal control chars. The former seems simpler and better. Typically one filters by log level or keyword anyway, that's what I think we should encourage at least

**Comment by fkaleo** [comment]
> We have instances which receive `>=300` requests on `/render` per second, so i think it's worth it to try to save allocations in this logging logic. There are currently a lot of temporary string variables getting allocated which then get concatenated into the logline if they're `!=""`, you could use something like `strings.Builder` and just directly write those string values and then pool the builders in a `sync.Pool` to reduce the number of allocations.

Using a `strings.Builder` since 001eef8 however I am not sure a `sync.Pool` would help much as allocating a new `strings.Builder` is probably as cheap as reusing an existing one on which we called `.Reset()`

File: api/middleware/logger.go (hunk 3 above)
Comment (fkaleo) [reply api/middleware/logger.go]: I'd like to preserve that compatibility with Cortex if that's ok with you?

File: api/middleware/logger.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+	"time"
+
+	opentracing "github.com/opentracing/opentracing-go"
+	log "github.com/sirupsen/logrus"
+	jaeger "github.com/uber/jaeger-client-go"
+	macaron "gopkg.in/macaron.v1"
+)
+
+var (
+	logHeaders = false
```
Comment (replay) [inline api/middleware/logger.go]: what's with this variable? should this be configurable?

Comment (fkaleo) [reply api/middleware/logger.go]: perhaps in the future, disabled by default for now.

**Comment by replay** [comment]
When adding config options they must also be added to `metrictank-sample.ini` (point 8 https://github.com/grafana/metrictank/blob/master/docs/CONTRIBUTING.md#when-contributing-prs) and then you can run `scripts/dev/sync-configs.sh` to sync the change to the other versions of the MT config in the repo
