### PR TITLE
Fix same models.Series getting added to the sync.Pool (or datamap) twice

### LINKED ISSUE #1875: Duplicate `Put` in point slice pool from `mergeSeries`
**Describe the bug**

In certain scenarios during a render request a slice can be returned to the pool 2 times. We saw corrupted responses because of this and so deployed a change that (within a single render) detects this case, does not return the slice to the pool twice and logs additional information. With this info I think I've found where it happens. In the (likely rare) case where there are identical time-series with 2 different intervals, [`mergeSeries`](https://github.com/grafana/metrictank/blob/001015d92537c73fedff18e3bb473f947bd1c80e/api/dataprocessor.go#L658) will merge them together to form a single normalized value. 

It then puts all the other series back into the pool and only keeps the first one. However, [`normalize`](https://github.com/grafana/metrictank/blob/001015d92537c73fedff18e3bb473f947bd1c80e/expr/normalize.go#L78) already puts the new normalized value into the datamap. So, in the scenario where there is series `foo.bar` with intervals 60 (let's call this `foo60`) and 30 (`foo30`) (in this order), the process flow goes something like:

1. `mergeSeries` calls `normalize(datamap, [foo60, foo30])`
1. `normalize` keeps `foo60` (nothing to do)
1. `normalize` copies `foo30`, consolidates it to 60 seconds and adds it to the datamap (let's call this `foo60_2`)
   - Note: At this point we dropped the slice from `foo30` to be GC'd. It did not go into the pool
1. `mergeSeries` then iterates over the points in `foo60` checking if it can fill `NaN` values from `foo60_2`
1. Finally, `mergeSeries` adds `foo60_2.Datapoints` into the pool, even though it is already in the datamap!

**Helpful Information**
Metrictank Version: ` v1.0-52` (custom build off of commit e0850173eac8153aa7dbb08d9de7b2ac12b529c8)
Golang Version:  `go1.12.7`

### PR DESCRIPTION
**Pull request by Dieterbe**
first commit introduces mostly comments and diagnosis
second commit fixes the issue and removes diagnosis

fix #1875 

Not supper happy with adding a bit of complexity, but seems like it's either this, or providing a bunch of alternative normalization functions that only differ in their side effects.

### CODE REVIEW

File: api/dataprocessor.go [hunk 1]
```diff
@@ -150,6 +153,7 @@ func divide(pointsA, pointsB []schema.Point) []schema.Point {
 	return pointsA
 }
 
+// getTargets retrieves the series for the given requests by querying remote and/or remote nodes as needed
```
Comment (shanson7) [inline api/dataprocessor.go:156]:
```suggestion
// getTargets retrieves the series for the given requests by querying local and/or remote nodes as needed
```

**Comment by shanson7** [comment]
I'll mention this as a possible alternative: We don't need to catch *every* point slice to put it back in the pool. IMO, it's ok to let some fall through. Not sure how common normalization is in practice, but we were running without `plan.Clean()` for pretty much the entirety of our deploy and didn't see too much of a difference after adding it.
